window.PORTFOLIO_PROJECTS = [
  {
    title: "Atlantic Exhibition",
    url: "https://atlanticexhibition.com",
    platform: "wordpress",
    source: "my-work",
    sourceLabel: "My work",
    summary: "Event website and automation-style business platform with a stronger corporate sales feel.",
    note: "Useful for WordPress, business website, SEO-aware structure, and process-led client work.",
    tags: ["wordpress", "php", "ecommerce", "seo", "marketing"],
    sites: ["tobi", "work", "marketing"],
  },
  {
    title: "KNP Talent Group",
    url: "https://knptalentgroup.com",
    platform: "wordpress",
    source: "my-work",
    sourceLabel: "My work",
    summary: "Corporate recruiting and talent brand site positioned for clarity, trust, and service communication.",
    note: "Sits well inside business WordPress work, brand polish, and service-site delivery.",
    tags: ["wordpress", "php", "seo", "content"],
    sites: ["tobi", "work", "marketing"],
  },
  {
    title: "Talosmart",
    url: "https://talosmart.com",
    platform: "wordpress",
    source: "my-work",
    sourceLabel: "My work",
    summary: "Agency-style web and mobile development presence covering multiple services and client entry points.",
    note: "Good reference for broader service websites and developer-led business positioning.",
    tags: ["wordpress", "php", "content", "marketing"],
    sites: ["tobi", "work", "marketing"],
  },
  {
    title: "Krestel Digital",
    url: "https://kresteldigital.com",
    platform: "wordpress",
    source: "my-work",
    sourceLabel: "My work",
    summary: "Digital services website for an ambitious brand with a cleaner agency and strategy tone.",
    note: "Fits both your growth page and your broad portfolio as a polished service-business example.",
    tags: ["wordpress", "seo", "marketing", "content"],
    sites: ["work", "marketing"],
  },
  {
    title: "Savvy Media Africa",
    url: "https://savvymediaafrica.com",
    platform: "wordpress",
    source: "my-work",
    sourceLabel: "My work",
    summary: "Media-forward brand site where messaging, content flow, and visual confidence matter.",
    note: "Helps the marketing and content side of the portfolio feel more grounded.",
    tags: ["wordpress", "marketing", "content", "seo"],
    sites: ["work", "marketing"],
  },
  {
    title: "Rex Clark Adventures",
    url: "https://rexclarkadventures.com",
    platform: "wordpress",
    source: "my-work",
    sourceLabel: "My work",
    summary: "Blog and travel-style content website with room for editorial structure and organic search support.",
    note: "A clean blog example for the SEO and content-led side of the portfolio.",
    tags: ["wordpress", "blog", "content", "seo"],
    sites: ["work", "marketing"],
  },
  {
    title: "Omiren Styles",
    url: "https://omirenstyles.com",
    platform: "wordpress",
    source: "my-work",
    sourceLabel: "My work",
    summary: "Fashion-oriented brand site that supports style presentation, product messaging, and content flow.",
    note: "Works as a blog, fashion, and brand-site reference for both store and content briefs.",
    tags: ["wordpress", "blog", "content", "ecommerce"],
    sites: ["work", "marketing"],
  },
  {
    title: "Tobi Holyprofweb",
    url: "https://tobi.holyprofweb.com",
    platform: "wordpress",
    source: "my-work",
    sourceLabel: "My work",
    summary: "Personal portfolio environment for organizing proof across development, marketing, and proposal use.",
    note: "Useful as proof of custom branding, structure, and portfolio presentation work.",
    tags: ["wordpress", "php", "content"],
    sites: ["tobi", "work"],
  },
  {
    title: "Stripe card saving on WordPress",
    url: "https://www.upwork.com/freelancers/holyprof1",
    platform: "wordpress",
    source: "upwork",
    sourceLabel: "Upwork case",
    summary: "Handled a Stripe setup focused on saving customer card details for charge-later and off-session payments.",
    note: "Best fit for payment integration, WordPress engineering, and API logic conversations.",
    tags: ["wordpress", "php", "api", "debugging", "fixes"],
    sites: ["tobi", "work", "dev"],
  },
  {
    title: "WordPress filter fix",
    url: "https://www.upwork.com/freelancers/holyprof1",
    platform: "wordpress",
    source: "upwork",
    sourceLabel: "Upwork case",
    summary: "Small but important troubleshooting work where a broken filter flow had to be fixed cleanly and quickly.",
    note: "Strong card for bug-fix proposals and maintenance work where the client needs confidence more than drama.",
    tags: ["wordpress", "fixes", "debugging", "php"],
    sites: ["tobi", "work", "dev"],
  },
  {
    title: "Shopify to Amazon setup and SEO support",
    url: "https://www.upwork.com/freelancers/holyprof1",
    platform: "shopify",
    source: "upwork",
    sourceLabel: "Upwork case",
    summary: "Supported store setup around Amazon approval, listing flow, and SEO-minded product visibility work.",
    note: "A useful bridge card for eCommerce, marketplace support, and product feed conversations.",
    tags: ["shopify", "ecommerce", "seo", "marketing"],
    sites: ["work", "marketing"],
  },
  {
    title: "Custom shipping for Ecwid",
    url: "https://www.upwork.com/freelancers/holyprof1",
    platform: "ecwid",
    source: "upwork",
    sourceLabel: "Upwork case",
    summary: "Implemented custom shipping logic for an Ecwid website where default store behavior was not enough.",
    note: "Strong proof for custom rules, eCommerce logic, and platform-specific store work.",
    tags: ["ecwid", "ecommerce", "php", "api", "automation"],
    sites: ["tobi", "work", "dev", "marketing"],
  },
  {
    title: "Google Shopping with Ecwid",
    url: "https://www.upwork.com/freelancers/holyprof1",
    platform: "ecwid",
    source: "upwork",
    sourceLabel: "Upwork case",
    summary: "Handled Google Shopping integration around feeds, Merchant Center, and store sync direction.",
    note: "Very useful for clients asking about product approval issues, feed cleanup, and visibility work.",
    tags: ["ecwid", "google-shopping", "ecommerce", "seo", "marketing"],
    sites: ["work", "marketing"],
  },
  {
    title: "PHP development support",
    url: "https://www.upwork.com/freelancers/holyprof1",
    platform: "php",
    source: "upwork",
    sourceLabel: "Upwork case",
    summary: "General-purpose PHP development work delivered in a short support window with a strong outcome.",
    note: "Simple card, but good reinforcement when the brief is direct and technical.",
    tags: ["php", "laravel", "debugging", "database"],
    sites: ["tobi", "work", "dev"],
  },
  {
    title: "Paywall pick system for sports leaderboard",
    url: "https://www.upwork.com/freelancers/holyprof1",
    platform: "php",
    source: "upwork",
    sourceLabel: "Upwork case",
    summary: "Custom PHP work on a paywalled sports leaderboard flow where business logic mattered.",
    note: "Great for developer-first discussions around custom features and business rules.",
    tags: ["php", "laravel", "api", "database", "automation"],
    sites: ["work", "dev"],
  },
  {
    title: "Mesfollow creator platform",
    url: "https://www.upwork.com/freelancers/holyprof1",
    platform: "php",
    source: "my-work",
    sourceLabel: "Portfolio case",
    summary: "Paid creator and social-style platform work referenced directly on the current Upwork profile.",
    note: "Useful when the client wants something more app-like than a standard brochure website.",
    tags: ["php", "laravel", "database", "api", "automation"],
    sites: ["tobi", "work", "dev"],
  },
  {
    title: "Docenti LMS",
    url: "https://lms.docentibusinessschool.com/",
    platform: "laravel",
    source: "my-work",
    sourceLabel: "My work",
    summary: "Learning platform setup with structured content delivery and a more application-driven workflow.",
    note: "A solid card for portals, dashboards, protected content, and education platforms.",
    tags: ["laravel", "php", "database", "content"],
    sites: ["tobi", "work", "dev"],
  },
  {
    title: "Docenti Business School",
    url: "https://docentibusinessschool.com/",
    platform: "wordpress",
    source: "my-work",
    sourceLabel: "My work",
    summary: "Business school site that complements the LMS side and shows clearer service plus education positioning.",
    note: "Helpful when pitching education, LMS, or content-heavy service websites.",
    tags: ["wordpress", "php", "content", "seo"],
    sites: ["tobi", "work", "marketing"],
  },
  {
    title: "Tubowoman",
    url: "https://tubowoman.com",
    platform: "shopify",
    source: "reference",
    sourceLabel: "Platform reference",
    summary: "Shopify storefront reference for eCommerce layout direction, product structure, and merchandising feel.",
    note: "Included as a style and platform reference, not claimed as your original build.",
    tags: ["shopify", "ecommerce"],
    sites: ["work"],
  },
  {
    title: "LML Planner",
    url: "https://lmlplanner.com",
    platform: "shopify",
    source: "reference",
    sourceLabel: "Platform reference",
    summary: "Shopify example with a more product-led presentation and a distinct brand personality.",
    note: "Useful when a client wants a store with strong visual product storytelling.",
    tags: ["shopify", "ecommerce"],
    sites: ["work"],
  },
  {
    title: "Allbirds",
    url: "https://www.allbirds.com",
    platform: "shopify",
    source: "reference",
    sourceLabel: "Platform reference",
    summary: "Well-known eCommerce reference for polished navigation, PDP structure, and conversion-minded store flow.",
    note: "Included as a benchmark reference for store quality and layout direction.",
    tags: ["shopify", "ecommerce"],
    sites: ["work"],
  },
  {
    title: "Gymshark",
    url: "https://row.gymshark.com",
    platform: "shopify",
    source: "reference",
    sourceLabel: "Platform reference",
    summary: "Strong storefront reference for performance, merchandising density, and modern brand energy.",
    note: "Useful when clients want a cleaner fitness or apparel eCommerce direction.",
    tags: ["shopify", "ecommerce", "marketing"],
    sites: ["work", "marketing"],
  },
  {
    title: "ColourPop",
    url: "https://colourpop.com",
    platform: "shopify",
    source: "reference",
    sourceLabel: "Platform reference",
    summary: "Beauty eCommerce reference with aggressive merchandising, campaigns, and launch-style presentation.",
    note: "A good benchmark for cosmetics, lifestyle, and high-turnover campaigns.",
    tags: ["shopify", "ecommerce", "marketing"],
    sites: ["work", "marketing"],
  },
  {
    title: "Dola Photo",
    url: "https://dolaphoto.com",
    platform: "squarespace",
    source: "reference",
    sourceLabel: "Platform reference",
    summary: "Squarespace portfolio-style reference for photography, branding, and personal service presentation.",
    note: "Useful for clients who want a softer portfolio aesthetic rather than a heavy business site.",
    tags: ["squarespace", "content"],
    sites: ["work"],
  },
  {
    title: "Jonn Donovan",
    url: "https://jonndonovan.com",
    platform: "squarespace",
    source: "reference",
    sourceLabel: "Platform reference",
    summary: "Squarespace reference with a more editorial personal-brand feel.",
    note: "Included as a structure and style direction reference.",
    tags: ["squarespace", "content"],
    sites: ["work"],
  },
  {
    title: "Mark Foster",
    url: "https://markfoster.net",
    platform: "squarespace",
    source: "reference",
    sourceLabel: "Platform reference",
    summary: "Squarespace personal-site reference for straightforward content-led presentation.",
    note: "Good for creator, coach, or consultant site direction.",
    tags: ["squarespace", "content"],
    sites: ["work"],
  },
  {
    title: "Beta Takaki",
    url: "https://betatakaki.com",
    platform: "squarespace",
    source: "reference",
    sourceLabel: "Platform reference",
    summary: "Portfolio reference with a cleaner visual-first presentation style.",
    note: "Useful for creative portfolio conversations and visual layout direction.",
    tags: ["squarespace", "content"],
    sites: ["work"],
  },
  {
    title: "Tyler Cellison",
    url: "https://www.tylercellison.com",
    platform: "squarespace",
    source: "reference",
    sourceLabel: "Platform reference",
    summary: "Squarespace portfolio reference for personal branding and media presentation.",
    note: "Included as a benchmark reference rather than claimed delivery.",
    tags: ["squarespace", "content"],
    sites: ["work"],
  },
  {
    title: "Aaron Dromero",
    url: "https://aarondromero.com",
    platform: "webflow",
    source: "reference",
    sourceLabel: "Platform reference",
    summary: "Webflow reference for motion, visual hierarchy, and premium portfolio pacing.",
    note: "Useful when a client wants a more custom-feeling, visual-first landing experience.",
    tags: ["webflow", "content", "marketing"],
    sites: ["work", "marketing"],
  },
  {
    title: "Rodukov",
    url: "https://rodukov.com",
    platform: "webflow",
    source: "reference",
    sourceLabel: "Platform reference",
    summary: "Webflow reference with cleaner art direction and more visual rhythm.",
    note: "Helps show range in site style even when the implementation stack differs.",
    tags: ["webflow", "content"],
    sites: ["work"],
  },
  {
    title: "Charli Marie",
    url: "https://charlimarie.com",
    platform: "webflow",
    source: "reference",
    sourceLabel: "Platform reference",
    summary: "Webflow creator-site reference for personality-driven portfolio storytelling.",
    note: "Good benchmark for creator brands and personal portfolio direction.",
    tags: ["webflow", "content"],
    sites: ["work"],
  },
  {
    title: "PHPFox support lane",
    url: "https://www.phpfox.com",
    platform: "phpfox",
    source: "reference",
    sourceLabel: "Platform lane",
    summary: "Included as a capability lane because community-driven PHP platforms still need setup, customization, fixes, and support.",
    note: "This card marks a support direction inside the broad work portfolio rather than a named client build.",
    tags: ["phpfox", "php", "database", "debugging"],
    sites: ["work", "dev"],
  },
  {
    title: "Node.js service lane",
    url: "https://nodejs.org",
    platform: "node",
    source: "reference",
    sourceLabel: "Engineering lane",
    summary: "A technical direction card to make room for backend service work, tooling, and JavaScript runtime conversations.",
    note: "Used to position your dev portfolio beyond CMS-only assumptions.",
    tags: ["node", "api", "automation", "database"],
    sites: ["dev"],
  },
  {
    title: "Rust tooling lane",
    url: "https://www.rust-lang.org",
    platform: "rust",
    source: "reference",
    sourceLabel: "Engineering lane",
    summary: "A systems-minded direction card for tooling, performance-sensitive components, and future-facing engineering briefs.",
    note: "This is a positioning card for the dev site, not a claimed client screenshot.",
    tags: ["rust", "automation", "api"],
    sites: ["dev"],
  },
];
